### ISSUE TITLE
Allow placeholders in timings

### ISSUE THREAD

**Issue by NiklasEi** [NiklasEi/CalendarEvents#1]
For example:
```
example: 
    timing: 
        occasion: "monday" 
        time: "x3:x0"
```

Should be the same as:
```
example:
    timing: 
        occasion: "monday" 
        time: "03:00, 03:10, 03:20, 03:30, 03:40, 03:50, 13:00, 13:10, 13:20, 13:30, 13:40, 13:50"
```
